name: LEMP Server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Docker Compose (v2)
        run: |
          sudo apt update
          sudo apt install docker-compose

      - name: Build Docker images
        run: docker compose build   

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Login to Amazon ECR   # ✅ ye step add karo
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Push Docker images
        run: docker compose push
